IBM/integrity-enforcer

enforcer/pkg/control/common/reqcontext.go, enforcer/pkg/control/enforcer/checkcontext.go, enforcer/pkg/control/sign/signstore.go
this change would append something like this to the context log
```
"request.maskedObjectHash":"74234e98 ... 92f982b90b"
```
=> add request hash value to context log

develop/signservice/signservice/cmd/signservice/main.go, develop/signservice/signservice/pkg/sign/sign.go, enforcer/pkg/apis/resourcesignature/v1alpha1/types.go, enforcer/pkg/control/common/common.go, enforcer/pkg/control/common/reqcontext.go, enforcer/pkg/control/sign/signstore.go
support `mutableAttrs` to allow specified attributes that will be changed after sign
=> add mutableAttrs function

enforcer/pkg/sign/pkix/pkix.go, scripts/x509-rs-sign.sh
- fix gpg signing script to use `rsig-<kind>-<name>` for ResourceSignature name
- add x509 signing script
- support self signed certificate
=> add x509 sign script & support self signed certcase

Makefile, ie-build.conf
- Fixed makefile
- Added IBM_ENV flag in env settings
=> Fixed makefile and added IBM_ENV flag in env settings

build/build.sh
- Fixed env variable in scripts
=> Fixed env variable in scripts

Makefile
- Env variable check done earlier
=> Fixed env variable check in makefile

Makefile, demo/quick-start/demo.sh
=> Added demo magic script

Makefile, build/build.sh, build/install-dependencies.sh, build/pipeline.sh, build/publish.sh, build/publish_images.sh, build/push_images_ocm.sh, build/run-code-lint.sh, build/run-e2e-tests.sh, build/run-unit-tests.sh, demo/quick-start/demo.sh, integrity-verifier-operator/Makefile, integrity-verifier-operator/bundle.Dockerfile, integrity-verifier-operator/index.Dockerfile, integrity-verifier-operator/test/create-kind-cluster.sh, integrity-verifier-operator/test/e2e/e2e_suite_test.go, integrity-verifier-operator/test/e2e/framework.go, integrity-verifier-operator/test/e2e/iv_resource.go, integrity-verifier-operator/test/e2e/resource.go, integrity-verifier-operator/test/e2e/utils.go, scripts/gen-hrm.sh, scripts/gpg-annotation-sign.sh, scripts/gpg-rs-sign.sh, scripts/x509-rs-sign.sh
=> Added missing license

docs/README_RESOURCE_SIGNATURE.md
- updated readme to include description regarding signature annotations
=> updated readme to include description regarding signature annotations

.travis.yml, Makefile, build/build.sh, build/build_images.sh, integrity-verifier-operator/Makefile
- Added no-cache flag for building images
=> Added no-cache flag for building images

OWNERS, docs/README_DEPLOY_IV_LOCAL.md, docs/README_QUICK.md, docs/package.json
- removed emails from documents
=> removed emails from documents

Makefile
- Fixed sonar setup in makefile
=> Fixed sonar setup in makefile

.travis.yml
- Enable sonar in travis build
=> Enable sonar in travis build

integrity-shield-operator/controllers/integrityshield.go, integrity-shield-operator/controllers/integrityshield_controller.go, integrity-shield-operator/controllers/suite_test.go, shield/pkg/shield/handler_test.go
- remove unused codes
- add test case for loading signature from handler_test.go and report denied request
- add test case for util functions in operator controller code
=> add test case for handler_test and update controller tests

shield/pkg/common/profile_test.go
=> fix common test

integrity-shield-operator/test/e2e/e2e_test.go, shield/pkg/common/common.go, shield/pkg/shield/checkFunctions.go, shield/pkg/shield/checkUtils.go, shield/pkg/shield/handler.go, shield/pkg/shield/runData.go, shield/pkg/shield/sign.go, shield/pkg/shield/signVerifier.go
- fix signpolicy e2etest issue
- fix ruletable issue
- update Event report condition
=> fix signpolicy test & ruletable nil issue

shield/pkg/util/mapnode/node.go, shield/pkg/util/mapnode/node_test.go
fix mapnode/diff so that it could get diffs from different types of values.
=> support type inconsistent update in mapnode/diff

integrity-shield-operator/bundle/manifests/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/manager/kustomization.yaml, ishield-build.conf
Updated version after changes in CRD
=> Updated version after changes in CRD

shield/pkg/util/yaml/yaml.go
- fix lint issue in yaml_test.go
=> fix yaml_test.go lint issue

integrity-shield-operator/controllers/integrityshield.go, integrity-shield-operator/resources/cr.go, integrity-shield-operator/resources/deploy.go, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/shieldConfigForIShield.yaml, integrity-shield-operator/test/e2e/e2e_test.go, shield/.gitignore, shield/cmd/ishield-server/webhook.go, shield/pkg/common/common.go, shield/pkg/common/reqcontext.go, shield/pkg/shield/checkFunctions.go, shield/pkg/shield/checkUtils.go, shield/pkg/shield/config/shieldconfig.go, shield/pkg/shield/handler.go, shield/pkg/shield/handler_test.go, shield/pkg/shield/sign.go, shield/pkg/shield/signVerifier.go, shield/pkg/shield/testdata/dr_0.json, shield/pkg/shield/utilValidation.go, shield/pkg/util/sign/pgp/pgp.go, shield/pkg/util/sign/x509/x509.go
- change message in AdmissionResponse so that users could understand what they should do to make their request allowed.
- update event message to make more consistent ones with AdmissiionResponse.
-
=> improve event and message texts for users 

shield/pkg/shield/handler_test.go, shield/pkg/shield/sign.go, shield/pkg/shield/utilValidation.go
- fix validation issue about undefined field
- improve validation of SignerConfig
- improve error message in case of secret setup error
=> improved format validation and error message

docs/README_CHECK_AND_TROUBLESHOOTING.md, docs/README_QUICK.md, scripts/list_rsig.sh, scripts/list_rsp.sh
- update README_QUICK with event checking
- add README_CHECK_AND_TROUBLESHOOTING for detail checking
- add two scripts, `list_rsp.sh` and `list_rsig.sh` for convenience
=> add troubleshooting doc and scripts

integrity-shield-operator/go.sum, shield/cmd/ishield-server/webhook.go, shield/go.mod, shield/go.sum, shield/pkg/shield/checkFunctions_test.go, shield/pkg/shield/checkcontext.go, shield/pkg/shield/handler.go, shield/pkg/shield/handler_test.go, shield/pkg/shield/ruleTable.go, shield/pkg/shield/runData.go, shield/pkg/shield/utilMutation.go, shield/pkg/util/logger/context.go, shield/pkg/util/logger/logger.go, shield/pkg/util/logger/logger_test.go, shield/pkg/util/mapnode/node_test.go
- fix logging inconsistency
- improve loader and cache clearing 
- update a dependency package version
=> create logger for each request instead of singleton

Makefile, integrity-shield-operator/cert/cert.go, integrity-shield-operator/config/rbac/role.yaml, integrity-shield-operator/controllers/integrityshield.go, integrity-shield-operator/controllers/integrityshield_controller.go, integrity-shield-operator/test/e2e/e2e_test.go, integrity-shield-operator/test/e2e/framework.go, ishield-build.conf, shield/pkg/common/common.go, shield/pkg/shield/checkUtils.go
- change Roles/ClusterRoles to satisfy least privilege
- change webhook cert duration to 2 years
- add event type annotation for filtering IntegrityShieldEvent
- fix e2e test issue around newly created NS
=> fix integrity shield roles/cert config and add event type annotation to IntegrityShieldEvent

Makefile, build/update-version.sh
Added make target and script to update version in necessary files after building bundle based on new version
=> Added make target and script to update version in nessary files

Makefile, integrity-shield-operator/controllers/suite_test.go
- fix delete ns issue of e2e test 
- fix possible timeout issue in operator unit test
=> fix e2e test delete error & fix op unit test timeout error

shield/pkg/shield/checkUtils.go
- trim event message string if the message has more than 1024 characters.
=> add trimming for event message

integrity-shield-operator/controllers/suite_test.go
- set a short interval time between operator reconciles for unit test in order to avoid update conflict 
- set limit number of reconcile trial for unit test
=> fix reconcile test in integrity-shield-operator unit test

shield/pkg/shield/checkUtils.go
- add sa in `olm` namespace to special sa list for ishield resource
=> add olm sa to conditions for ishield resource special sa

build/update-version.sh, develop/local-deploy/operator_local.yaml, docs/ACM/README_DISABLE_ISHIELD_PROTECTION_ACM_ENV.md, integrity-shield-operator/Makefile, integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/manager/kustomization.yaml, integrity-shield-operator/config/manifests/bases/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/resources/default-ishield-cr.yaml, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/integrityShieldCR.yaml, integrity-shield-operator/resources/testdata/integrityShieldCRForTest.yaml, ishield-build.conf, scripts/install_shield.sh, shield/pkg/util/mapnode/node_test.go, shield/version/version.go
- version upgraded from 0.1.3 to 0.1.4
- made version changes in all necessary files
=> version upgraded from 0.1.3 to 0.1.4

integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml
- updated csv based on latest changes on cr
=> updated csv based on latest changes on cr

integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/manifests/bases/integrity-shield-operator.clusterserviceversion.yaml
- Description field need to be added for csv.
=> Added description to CSV metadata

build/unit-test-gpg-rs-sign.sh, scripts/generate_rsp.sh, scripts/gpg-annotation-sign.sh, scripts/gpg-annotation-verify.sh, scripts/gpg-rs-sign-verify.sh, scripts/gpg-rs-sign.sh, scripts/x509-rs-sign.sh
-Change tmp file location, rm tmp file after generation, 
- support for multi yaml 
- support for version: yq 3 and yq 4
=> Fixed signing scripts

integrity-shield-operator/resources/testdata/integrityShieldCR.yaml, shield/pkg/common/reqcontext.go, shield/pkg/shield/signVerifier.go, shield/pkg/shield/utilMutation.go, shield/pkg/util/mapnode/diff.go
- update to show only found diff keys for Secret request
=> avoid to show diff value for specific kind request

integrity-shield-operator/resources/default-ishield-cr.yaml, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/integrityShieldCR.yaml
=> disable observer by default

integrity-shield-operator/bundle/manifests/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/config/crd/bases/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/test/deploy/ishield-config-update.yaml
- remove `unprotectAttrs` in CRD files
- remove it in testdata
=> remove remaining `unprotectAttrs`

docs/ACM/README_SETUP_KEY_RING_ACM_ENV.md, scripts/ACM/acm-verification-key-setup.sh
- update key setup script with argparse
- update a doc related to the script
=> update key setup script and doc

shield/pkg/util/kubeutil/kubeutil.go
- fix a function to get kubeconfig for test
=> fix kubeconfig function for test

docs/ACM/README_SETUP_KEY_RING_ACM_ENV.md
- add `-` to key setup command in a document for fix
=> fix key setup command in doc

integrity-shield-operator/api/v1alpha1/zz_generated.deepcopy.go, integrity-shield-operator/bundle/manifests/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/config/crd/bases/apis.integrityshield.io_integrityshields.yaml, shield/pkg/apis/resourcesigningprofile/v1alpha1/types.go, shield/pkg/apis/resourcesigningprofile/v1alpha1/zz_generated.deepcopy.go
- enable `unprotectAttrs` again for backward compatibility
=> enable `unprotectAttrs` again for backward compatibility

integrity-shield-operator/config/manager/manager.yaml, integrity-shield-operator/resources/deploy.go, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml
- add liveness & readiness probes to all containers including operator
=> set probes and update testdata

shield/pkg/common/common.go, shield/pkg/common/policy.go, shield/pkg/shield/checkcontext.go, shield/pkg/shield/sign.go, shield/pkg/shield/signVerifier.go, shield/pkg/util/sign/pgp/pgp.go, shield/pkg/util/sign/pgp/pgp_test.go, shield/pkg/util/sign/x509/x509.go, shield/pkg/util/sign/x509/x509_test.go
- fix signature verification flow to follow signer config structure
- get pgp public key finger print
=> fix sign verifier flow based on signer config

scripts/gpg-rs-sign.sh, scripts/list_rsp.sh
- fix bugs in list-rsp.sh & gpg-rs-sign.sh
=> fix small bugs of scripts

integrity-shield-operator/config/crd/bases/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/config/samples/apis_v1alpha1_integrityshield.yaml, integrity-shield-operator/config/samples/apis_v1alpha1_integrityshield_local.yaml, integrity-shield-operator/test/e2e/e2e_test.go, shield/pkg/client/resourcesigningprofile/clientset/versioned/fake/register.go, shield/pkg/common/profile.go, shield/pkg/common/profile_test.go, shield/pkg/util/mapnode/node_test.go, shield/pkg/util/mapnode/testdata/data4.json
- update ns override attr (originalNamespace --> allowNamespaceChange)
- update CRDs
- update e2e test in terms of error handling
=> update ns override attr & update CRDs

Makefile, develop/local-deploy/operator_local.yaml, docs/ACM/README_DISABLE_ISHIELD_PROTECTION_ACM_ENV.md, integrity-shield-operator/Makefile, integrity-shield-operator/bundle/manifests/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/crd/bases/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/config/manager/kustomization.yaml, integrity-shield-operator/config/manifests/bases/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/samples/apis_v1alpha1_integrityshield.yaml, integrity-shield-operator/config/samples/apis_v1alpha1_integrityshield_local.yaml, integrity-shield-operator/resources/default-ishield-cr.yaml, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/integrityShieldCR.yaml, integrity-shield-operator/resources/testdata/integrityShieldCRForTest.yaml, integrity-shield-operator/test/e2e/e2e_test.go, ishield-build.conf, scripts/install_shield.sh, shield/pkg/client/resourcesigningprofile/clientset/versioned/fake/register.go, shield/pkg/common/profile.go, shield/pkg/common/profile_test.go, shield/pkg/util/mapnode/node_test.go, shield/pkg/util/mapnode/testdata/data4.json, shield/version/version.go
- Upgraded OLM bundle from 0.1.4 to 0.1.5
-  Fixed version in respective files.
=> Upgraded OLM bundle from 0.1.4 to 0.1.5

develop/local-deploy/operator_local.yaml, docs/ACM/README_DISABLE_ISHIELD_PROTECTION_ACM_ENV.md, integrity-shield-operator/Makefile, integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/manager/kustomization.yaml, integrity-shield-operator/config/manifests/bases/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/resources/default-ishield-cr.yaml, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/integrityShieldCR.yaml, integrity-shield-operator/resources/testdata/integrityShieldCRForTest.yaml, ishield-build.conf, scripts/install_shield.sh, shield/version/version.go
- operator bundle version upgraded from 0.1.5 to 0.1.6
- version updated in corresponding files
=> operator bundle version upgraded from 0.1.5 to 0.1.6

docs/ACM/README_CLUSTER_UPGRADE.md, docs/README_LIMITATION.md
- add a documentation of explicit limitation of Integrity Shield; signature protection availability during cluster upgrade
=> add limitation documentation

integrity-shield-operator/test/deploy/test-deployment-update.yaml, integrity-shield-operator/test/deploy/test-deployment.yaml, integrity-shield-operator/test/deploy/test-rsp-update.yaml, integrity-shield-operator/test/e2e/e2e_test.go, integrity-shield-operator/test/e2e/framework.go, integrity-shield-operator/test/e2e/resource.go, shield/pkg/shield/signVerifier.go
- fix an issue which is happened when kubectl apply is used for update request
- add e2e test cases for the issue
=> support update with kubectl apply by default

Makefile, cmd/cli/signyaml.go, cmd/cli/signyamlverify_test.go, cmd/cli/verifyyaml.go, cmd/pkg/yamlsign/util.go, cmd/test/data/test_configmap.yaml
- Added test code for sign/verify yaml
=> Added tests code for signing and verifying YAML

develop/local-deploy/operator_local.yaml, docs/ACM/README_DISABLE_ISHIELD_PROTECTION_ACM_ENV.md, integrity-shield-operator/Makefile, integrity-shield-operator/bundle/manifests/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/bundle/manifests/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/config/crd/bases/apis.integrityshield.io_integrityshields.yaml, integrity-shield-operator/config/manager/kustomization.yaml, integrity-shield-operator/config/manifests/bases/integrity-shield-operator.clusterserviceversion.yaml, integrity-shield-operator/resources/default-ishield-cr.yaml, integrity-shield-operator/resources/testdata/deploymentForIShield.yaml, integrity-shield-operator/resources/testdata/integrityShieldCR.yaml, integrity-shield-operator/resources/testdata/integrityShieldCRForTest.yaml, ishield-build.conf, scripts/install_shield.sh, shield/version/version.go
-  Upgraded operator to version 0.2.0
=> Fix/upgrade 0 2.0

integrity-shield-operator/config/samples/apis_v1_integrityshield.yaml, integrity-shield-operator/config/samples/apis_v1_integrityshield_ac.yaml, integrity-shield-operator/config/samples/apis_v1_integrityshield_local.yaml
Signed-off-by: ruriko <rurikudo@ibm.com>
- fix format of constraint config in CR
=> fix format of constraint config in CR

integrity-shield-operator/config/manager/kustomization.yaml, observer/pkg/observer/observer.go, observer/pkg/observer/verify_resource.go, shield/pkg/config/request_handler_config.go, shield/pkg/shield/request_handler.go
Signed-off-by: ruriko <rurikudo@ibm.com>
- enable to use private rekor server
- rekor server url can be set in sigstoreConfig
=> enable to use private rekor server

integrity-shield-operator/controllers/integrityshield.go, integrity-shield-operator/controllers/integrityshield_controller.go, integrity-shield-operator/resources/role.go
Signed-off-by: ruriko <rurikudo@ibm.com>
- change api and observer roles to the minimum privileges
=> change roles to the minimum privileges
